baseURL: https://example.com
defaultContentLanguage: en
theme: LoveIt
title: LoveIt
enableRobotsTXT: yes
enableGitInfo: yes
enableEmoji: yes
languages:
  en:
    copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
      4.0 International License.
    googleAnalytics: ''
    hasCJKLanguage: no
    languageCode: en
    languageName: English
    menu:
      main:
        - identifier: posts
          name: Posts
          post: ''
          pre: ''
          title: ''
          url: /posts/
          weight: 1
        - identifier: tags
          name: Tags
          post: ''
          pre: ''
          title: ''
          url: /tags/
          weight: 2
        - identifier: categories
          name: Categories
          post: ''
          pre: ''
          title: ''
          url: /categories/
          weight: 3
        - identifier: documentation
          name: Docs
          post: ''
          pre: ''
          title: ''
          url: /categories/documentation/
          weight: 4
        - identifier: about
          name: About
          post: ''
          pre: ''
          title: ''
          url: /about/
          weight: 5
        - identifier: github
          name: ''
          post: ''
          pre: <i class='fab fa-github fa-fw'></i>
          title: GitHub
          url: https://github.com/dillonzq/LoveIt
          weight: 6
    paginate: 12
    params:
      app:
        iconColor: '#5bbad5'
        noFavicon: no
        svgFavicon: ''
        themeColor: '#ffffff'
        tileColor: '#da532c'
        title: LoveIt
      description: About LoveIt Theme
      home:
        posts:
          enable: yes
          paginate: 6
        profile:
          avatarURL: /images/avatar.png
          disclaimer: ''
          enable: yes
          gravatarEmail: ''
          social: yes
          subtitle: A Clean, Elegant but Advanced Hugo Theme
          title: ''
          typeit: yes
        rss: 10
      keywords:
        - Theme
        - Hugo
      search:
        absoluteURL: no
        algolia:
          appID: PASDMWALPK
          index: index.en
          searchKey: b42948e51daaa93df92381c8e2ac0f93
        contentLength: 4000
        enable: yes
        highlightTag: em
        maxResultLength: 10
        placeholder: ''
        snippetLength: 30
        type: algolia
      social:
        Angellist: ''
        Bandcamp: ''
        Behance: ''
        Bilibili: ''
        Bitbucket: ''
        Codepen: ''
        Deviantart: ''
        Devto: ''
        Douban: ''
        Dribbble: ''
        Email: xxxx@xxxx.com
        Facebook: xxxx
        Fivehundredpx: ''
        Flickr: ''
        Foursquare: ''
        FreeCodeCamp: ''
        GitHub: xxxx
        Gitea: ''
        Gitlab: ''
        Goodreads: ''
        Googlescholar: ''
        Hackernews: ''
        Instagram: xxxx
        Jsfiddle: ''
        Keybase: ''
        Kickstarter: ''
        Lastfm: ''
        Linkedin: ''
        Mastodon:
          id: '@xxxx'
          prefix: https://mastodon.technology/
        Matrix: ''
        Medium: ''
        Mix: ''
        Odnoklassniki: ''
        Patreon: ''
        Paypal: ''
        Pinterest: ''
        Quora: ''
        RSS: yes
        Reddit: ''
        Researchgate: ''
        Skype: ''
        Slidershare: ''
        Snapchat: ''
        Soundcloud: ''
        Spotify: ''
        Stackoverflow: ''
        Steam: ''
        Strava: ''
        Telegram: xxxx
        Thingiverse: ''
        Tumblr: ''
        Twitch: ''
        Twitter: xxxx
        VK: ''
        Vine: ''
        Weibo: ''
        Whatsapp: ''
        Wordpress: ''
        XMPP: ''
        Xing: ''
        Youtubechannel: ''
        Youtubecustom: ''
        Youtubelegacy: xxxx
        Zhihu: ''
    weight: 1
  fr:
    copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
      4.0 International License.
    googleAnalytics: ''
    hasCJKLanguage: no
    languageCode: fr
    languageName: Français
    menu:
      main:
        - identifier: posts
          name: Postes
          post: ''
          pre: ''
          title: ''
          url: /posts/
          weight: 1
        - identifier: tags
          name: Balises
          post: ''
          pre: ''
          title: ''
          url: /tags/
          weight: 2
        - identifier: categories
          name: Catégories
          post: ''
          pre: ''
          title: ''
          url: /categories/
          weight: 3
        - identifier: documentation
          name: Docs
          post: ''
          pre: ''
          title: ''
          url: /categories/documentation/
          weight: 4
        - identifier: about
          name: À propos
          pre: ''
          title: ''
          url: /about/
          weight: 5
        - identifier: github
          name: ''
          post: ''
          pre: <i class='fab fa-github fa-fw'></i>
          title: GitHub
          url: https://github.com/dillonzq/LoveIt
          weight: 6
    paginate: 12
    params:
      app:
        iconColor: '#5bbad5'
        noFavicon: no
        svgFavicon: ''
        themeColor: '#ffffff'
        tileColor: '#da532c'
        title: LoveIt
      description: À propos du thème LoveIt
      home:
        posts:
          enable: yes
          paginate: 6
        profile:
          avatarURL: /images/avatar.png
          disclaimer: ''
          enable: yes
          gravatarEmail: ''
          social: yes
          subtitle: Un thème Hugo simple, élégant et efficace
          title: ''
          typeit: yes
        rss: 10
      keywords:
        - Thème
        - Hugo
      search:
        absoluteURL: no
        algolia:
          appID: PASDMWALPK
          index: index.fr
          searchKey: b42948e51daaa93df92381c8e2ac0f93
        contentLength: 4000
        enable: yes
        highlightTag: em
        maxResultLength: 10
        placeholder: ''
        snippetLength: 30
        type: algolia
      social:
        Angellist: ''
        Bandcamp: ''
        Behance: ''
        Bilibili: ''
        Bitbucket: ''
        Codepen: ''
        Deviantart: ''
        Devto: ''
        Douban: ''
        Dribbble: xxxx
        Email: xxxx@xxxx.com
        Facebook: ''
        Fivehundredpx: ''
        Flickr: ''
        Foursquare: ''
        FreeCodeCamp: ''
        GitHub: xxxx
        Gitea: ''
        Gitlab: ''
        Goodreads: ''
        Googlescholar: ''
        Hackernews: xxxx
        Instagram: ''
        Jsfiddle: ''
        Keybase: ''
        Kickstarter: ''
        Lastfm: ''
        Linkedin: xxxx
        Mastodon: ''
        Matrix: ''
        Medium: ''
        Mix: ''
        Odnoklassniki: ''
        Patreon: ''
        Paypal: ''
        Pinterest: ''
        Quora: ''
        RSS: yes
        Reddit: ''
        Researchgate: ''
        Skype: ''
        Slidershare: ''
        Snapchat: xxxx
        Soundcloud: ''
        Spotify: ''
        Stackoverflow: ''
        Steam: ''
        Strava: ''
        Telegram: ''
        Thingiverse: ''
        Tumblr: ''
        Twitch: ''
        Twitter: xxxx
        VK: ''
        Vine: ''
        Weibo: ''
        Whatsapp: ''
        Wordpress: ''
        XMPP: ''
        Xing: ''
        Youtubechannel: ''
        Youtubecustom: ''
        Youtubelegacy: ''
        Zhihu: ''
    weight: 3
  zh-cn:
    copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
      4.0 International License.
    googleAnalytics: ''
    hasCJKLanguage: yes
    languageCode: zh-CN
    languageName: 简体中文
    menu:
      main:
        - identifier: posts
          name: 所有文章
          post: ''
          pre: ''
          title: ''
          url: /posts/
          weight: 1
        - identifier: tags
          name: 标签
          post: ''
          pre: ''
          title: ''
          url: /tags/
          weight: 2
        - identifier: categories
          name: 分类
          post: ''
          pre: ''
          title: ''
          url: /categories/
          weight: 3
        - identifier: documentation
          name: 文档
          pre: ''
          title: ''
          url: /categories/documentation/
          weight: 4
        - identifier: about
          name: 关于
          post: ''
          pre: ''
          title: ''
          url: /about/
          weight: 5
        - identifier: github
          name: ''
          post: ''
          pre: <i class='fab fa-github fa-fw'></i>
          title: GitHub
          url: https://github.com/dillonzq/LoveIt
          weight: 6
    paginate: 12
    params:
      app:
        iconColor: '#5bbad5'
        noFavicon: no
        svgFavicon: ''
        themeColor: '#ffffff'
        tileColor: '#da532c'
        title: LoveIt
      description: 关于 LoveIt 主题
      home:
        posts:
          enable: yes
          paginate: 6
        profile:
          avatarURL: /images/avatar.png
          disclaimer: ''
          enable: yes
          gravatarEmail: ''
          social: yes
          subtitle: 一个简洁、优雅且高效的 Hugo 主题
          title: ''
          typeit: yes
        rss: 10
      keywords:
        - Theme
        - Hugo
      search:
        absoluteURL: no
        algolia:
          appID: PASDMWALPK
          index: index.zh-cn
          searchKey: b42948e51daaa93df92381c8e2ac0f93
        contentLength: 4000
        enable: yes
        highlightTag: em
        maxResultLength: 10
        placeholder: ''
        snippetLength: 50
        type: algolia
      social:
        Angellist: ''
        Bandcamp: ''
        Behance: ''
        Bilibili: xxxx
        Bitbucket: ''
        Codepen: ''
        Deviantart: ''
        Devto: xxxx
        Douban: xxxx
        Dribbble: ''
        Email: xxxx@xxxx.com
        Facebook: ''
        Fivehundredpx: ''
        Flickr: ''
        Foursquare: ''
        FreeCodeCamp: ''
        GitHub: xxxx
        Gitea: ''
        Gitlab: ''
        Goodreads: ''
        Googlescholar: ''
        Hackernews: ''
        Instagram: ''
        Jsfiddle: ''
        Keybase: ''
        Kickstarter: ''
        Lastfm: ''
        Linkedin: ''
        Mastodon: ''
        Matrix: ''
        Medium: ''
        Mix: ''
        Odnoklassniki: ''
        Patreon: ''
        Paypal: ''
        Pinterest: ''
        Quora: ''
        RSS: yes
        Reddit: ''
        Researchgate: ''
        Skype: ''
        Slidershare: ''
        Snapchat: ''
        Soundcloud: ''
        Spotify: ''
        Stackoverflow: ''
        Steam: xxxx
        Strava: ''
        Telegram: ''
        Thingiverse: ''
        Tumblr: ''
        Twitch: ''
        Twitter: ''
        VK: ''
        Vine: ''
        Weibo: xxxx
        Whatsapp: ''
        Wordpress: ''
        XMPP: ''
        Xing: ''
        Youtubechannel: ''
        Youtubecustom: ''
        Youtubelegacy: ''
        Zhihu: xxxx
    weight: 2
params:
  analytics:
    enable: no
    fathom:
      id: ''
      server: ''
    google:
      anonymizeIP: yes
      id: ''
  cdn:
    data: jsdelivr.yml
  compatibility:
    objectFit: no
    polyfill: no
  cookieconsent:
    content:
      dismiss: ''
      link: ''
      message: ''
    enable: no
  dateFormat: '2006-01-02'
  defaultTheme: auto
  fingerprint: ''
  footer:
    author: yes
    copyright: yes
    custom: ''
    enable: yes
    hugo: yes
    icp: ''
    license: <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/"
      target="_blank">CC BY-NC 4.0</a>
    since: 2019
  gitRepo: https://github.com/dillonzq/LoveIt
  header:
    desktopMode: fixed
    mobileMode: auto
    title:
      logo: ''
      name: LoveIt
      post: ''
      pre: <i class='far fa-kiss-wink-heart fa-fw'></i>
      typeit: no
  images: /logo.png
  list:
    dateFormat: 01-02
    paginate: 20
    rss: 10
  page:
    code:
      copy: yes
      maxShownLines: 10
    comment:
      commento:
        enable: no
      disqus:
        enable: no
        shortname: ''
      enable: yes
      facebook:
        appId: ''
        enable: no
        languageCode: ''
        numPosts: 10
        width: 100%
      gitalk:
        clientId: ''
        clientSecret: ''
        enable: no
        owner: ''
        repo: ''
      telegram:
        color: ''
        colorful: yes
        dislikes: no
        enable: no
        height: ''
        limit: 5
        outlined: no
        siteID: ''
      utterances:
        darkTheme: github-dark
        enable: no
        issueTerm: pathname
        label: ''
        lightTheme: github-light
        repo: ''
      valine:
        appId: QGzwQXOqs5JOhN4RGPOkR2mR-MdYXbMMI
        appKey: WBmoGyJtbqUswvfLh6L8iEBr
        avatar: mp
        emoji: ''
        enable: yes
        enableQQ: no
        highlight: yes
        lang: ''
        meta: ''
        pageSize: 10
        placeholder: ''
        recordIP: yes
        serverURLs: https://leancloud.hugoloveit.com
        visitor: yes
    fontawesome: yes
    fraction: yes
    hiddenFromHomePage: no
    hiddenFromSearch: no
    library:
      css: {}
      js: {}
    lightgallery: no
    linkToMarkdown: yes
    mapbox:
      accessToken: pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ
      darkStyle: mapbox://styles/mapbox/dark-v10?optimize=true
      fullscreen: yes
      geolocate: yes
      lightStyle: mapbox://styles/mapbox/light-v10?optimize=true
      navigation: yes
      scale: yes
    math:
      blockLeftDelimiter: ''
      blockRightDelimiter: ''
      copyTex: yes
      enable: no
      inlineLeftDelimiter: ''
      inlineRightDelimiter: ''
      mhchem: yes
    rssFullText: no
    ruby: yes
    seo:
      images: []
      publisher:
        logoUrl: /images/avatar.png
        name: xxxx
    share:
      Baidu: no
      Blogger: no
      Buffer: no
      Digg: no
      Evernote: no
      Facebook: yes
      Flipboard: no
      HackerNews: yes
      Instapaper: no
      Line: yes
      Linkedin: no
      Mix: no
      Myspace: no
      Odnoklassniki: no
      Pinterest: no
      Pocket: no
      Reddit: no
      Renren: no
      Skype: no
      Stumbleupon: no
      Trello: no
      Tumblr: no
      Twitter: yes
      VK: no
      Weibo: yes
      Whatsapp: no
      Xing: no
      enable: yes
    toc:
      auto: yes
      enable: yes
      keepStatic: no
    twemoji: no
  section:
    dateFormat: 01-02
    paginate: 20
    rss: 10
  seo:
    image: /images/Apple-Devices-Preview.png
    thumbnailUrl: /images/screenshot.png
  typeit:
    cursorChar: '|'
    cursorSpeed: 1000
    duration: -1
    speed: 100
  verification:
    baidu: ''
    bing: ''
    google: ''
    pinterest: ''
    yandex: ''
  version: 0.2.X
markup:
  goldmark:
    extensions:
      definitionList: yes
      footnote: yes
      linkify: yes
      strikethrough: yes
      table: yes
      taskList: yes
      typographer: yes
    renderer:
      unsafe: yes
  highlight:
    codeFences: yes
    guessSyntax: yes
    lineNos: yes
    lineNumbersInTable: yes
    noClasses: no
  tableOfContents:
    endLevel: 6
    startLevel: 2
author:
  email: ''
  link: ''
  name: xxxx
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
Permalinks:
  posts: :filename
privacy:
  googleAnalytics: {}
  twitter:
    enableDNT: yes
  youtube:
    privacyEnhanced: yes
mediaTypes:
  text/plain:
    suffixes: md
outputFormats:
  MarkDown:
    isHTML: no
    isPlainText: yes
    mediaType: text/plain
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - MarkDown
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm: HTML
