baseurl: https://klaustrista.xyz
title: Klaus & Trista's daily
author: Klaus Gong
canonifyurls: yes
languagecode: en
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/favicon.jpg
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
    - stan
  progressively: no
  sitename: Klaus & Trista's Daily
  uselatex: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: GitHub
      url: https://github.com/klausegong
      weight: 3
    - name: Facebook
      url: https://twitter.com/nanxstats
      weight: 4
    - name: Vlog
      url: https://www.bilibili.com/video/BV17q4y1H7KL?from=search&seid=15212200060406723459&spm_id_from=333.337.0.0
      weight: 5
