baseurl: https://klaustrista.xyz
languageCode: en
defaultContentLanguage: en
title: Klaus & Trista's daily 
theme: hugo-theme-dream
params:
  author: Klaus
  avatar: /img/avatar.jpeg
  background: '#f7f7f7'
  email: klausegong@gmail.com
  headerTitle: Klaus & Trista's daily
  linkColor: seagreen
  motto: La vie en rose
  siteStartYear: 2021
